#Example (Hello, World):
from codeop import CommandCompiler
from distutils.command.config import config
from distutils.dir_util import create_tree
from os import terminal_size
import tkinter
from tkinter import messagebox #in python 3.x: tkinter wird kleingeschrieben
import webbrowser

tk = tkinter.Tk()

frame = tkinter.Frame(tk, relief="ridge", borderwidth=5)
frame.pack(fill="both",expand=1)
label = tkinter.Label(frame, text="v.0.0.1")
label.pack(expand=2)
label2 = tkinter.Label(frame, text="Streets of London Lyrics [Teil 1/2]")
label2.pack(expand=2)
label3 = tkinter.Label(frame, text="----------------------------------------------------------------------------------------------------- ")
label3.pack(expand=2)
label4 = tkinter.Label(frame, text="Have you seen the old man")
label4.pack(expand=2)
label5 = tkinter.Label(frame, text="In the closed down market")
label5.pack(expand=2)
label4 = tkinter.Label(frame, text="Kicking up the papers")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="With his worn out shoes?")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="In his eyes, you see no pride")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Hand held loosely at his side")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Yesterday's paper")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Telling yesterday's news")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="So, how can you tell me you're lonely")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="And say for you that the sun don't shine?")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Let me take you by the hand")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="And lead you through the streets of London")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Show you something to make you change your mind")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Have you seen the old girl")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Who walks the streets of London")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Dirt in her hair")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="And her clothes in rags?")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="She's no time for talking")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="She just keeps right on walking")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Carrying her home")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="In two carrier bags")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="So, how can you tell me you're lonely")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="And say for you that the sun don't shine?")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Let me take you by the hand")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="And lead you through the streets of London")
label4.pack(expand=2)
label4 = tkinter.Label(frame, text="Show you something to make you change your mind")
label4.pack(expand=2)
label3 = tkinter.Label(frame, text="----------------------------------------------------------------------------------------------------- ")
label3.pack(expand=2)

button = tkinter.Button(frame,text="Exit",command=tk.destroy) #.destroy
button.pack(side="bottom")

tk.mainloop()